#ifndef GLOBALS_H_INCLUDED
#define GLOBALS_H_INCLUDED

#define BURNMODE_PERI 0
#define BURNMODE_APO  1
#define BURNMODE_MAN  2
#define BURNMODE_TGT  3

#define INPUTMODE_NONE 0
#define INPUTMODE_DV 1
#define INPUTMODE_TARGET 2
#define INPUTMODE_OFFSET 3
#define INPUTMODE_TIME 4
#define INPUTMODE_EXTRA 5
#define INPUTMODE_MFDSEL 6

#endif // GLOBALS_H_INCLUDED
